language: cpp
compiler: 
  - gcc
os:
  - linux
branches:
    only:
      - left4monsters
      - item_random
      - phrases
      - weapon_medkit
sudo: true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-multilib g++-multilib; fi
script:
  - mkdir -p build && cd build
  - cmake ../ && make -j3
