#pragma once
#ifndef SENTENCES_H
#define SENTENCES_H

#define CBSENTENCENAME_MAX 16

#define CVOXFILESENTENCEMAX_GOLDSOURCE_LEGACY 1536
#define CVOXFILESENTENCEMAX_GOLDSOURCE_ANNIVERSARY_25 2048
#define CVOXFILESENTENCEMAX_XASH3D 4096
#define CVOXFILESENTENCEMAX CVOXFILESENTENCEMAX_XASH3D

#endif
