name: msvc6 build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache old msvc
      id: cache-old-msvc
      uses: actions/cache@v2
      with:
        path: shtudio.7z
        key: ${{ runner.os }}-old-msvc
    - name: Download old msvc
      if: steps.cache-old-msvc.outputs.cache-hit != 'true'
      run: wget --no-verbose https://github.com/FWGS/shtudio/raw/master/shtudio.7z
    - name: Build with old msvc using wine
      run: |
        p7zip --keep -d shtudio.7z
        sudo dpkg --add-architecture i386
        sudo apt -qq update
        sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
        sudo apt install wine wine32
        MSVCDir=z:/$PWD/vsmini sh -c '(cd dlls && wine cmd /c compile.bat) && (cd cl_dll && wine cmd /c compile.bat)'
        mkdir -p oldwindows/dlls
        mkdir -p oldwindows/cl_dlls
        cp dlls/hl.dll oldwindows/dlls/
        cp cl_dll/client.dll oldwindows/cl_dlls/
        cp fgd/halflife.fgd oldwindows/halflife.fgd
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')"
      id: extract_branch
    - name: Upload old msvc artifact
      uses: actions/upload-artifact@v2
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows-xp
        path: oldwindows
